version: '3.7'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  auth:
    depends_on:
      - nginx
    restart: always
    build:       
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./auth:/app